package/aichat:require SSE and SSE2 on i386 target
This commit adds a new dependency to check for SSE & SSE2 support
when building for i386 targets. This check is needed to prevent build
failures due to unsupported instructions.

The idea is to keep the package available for all non-i386 targets,
but in case of i386 also check additionally that the SSE & SSE2 flags
are set.

The problem was discovered by autobuild [1] and looks like:

	error[E0080]: evaluation panicked: assertion failed: cfg!(target_feature = "sse") && cfg!(target_feature = "sse2")
    --> /home/autobuild/autobuild/instance-38/output-1/build/aichat-0.30.0/VENDOR/ring/src/cpu/intel.rs:26:9
       |
    26 |         assert!(cfg!(target_feature = "sse") && cfg!(target_feature = "sse2"));
       |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    evaluation of `cpu::intel::abi_assumptions::_ASSUMES_SSE2` failed here

[1] https://autobuild.buildroot.org/results/c38a21c80490d5012c5b7bd926e778b406b5f26a/build-end.log

Signed-off-by: Alexander Shirokov <shirokovalexs@gmail.com>